trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformCLI@2
      inputs:
        command: 'init'
        allowTelemetryCollection: false

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-var "subscription_id=$(subscription_id)" -var "tenant_id=$(tenant_id)" -var "client_id=$(client_id)" -var "client_secret=$(client_secret)"'
        environmentServiceNameAzureRM: 'AzureDevops-AzureARM SC'
- stage: Deploy
  displayName: 'Terraform Apply'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - task: TerraformCLI@2
      inputs:
        command: 'init'
        allowTelemetryCollection: false
    - task: TerraformCLI@2
      inputs:
        command: 'apply'
        environmentServiceName: 'AzureDevops-AzureARM SC'
        allowTelemetryCollection: false