trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure subscription 1(b98d2b8d-4039-4e94-a202-67c3a82a3ced)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)
          az account set --subscription $(subscription_id)
    - script: |
        terraform --version
        terraform init 
        terraform plan -out=tfplan
      displayName: 'Az login & Terraform Init and Plan'

- stage: Deploy
  displayName: 'Terraform Apply'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
        
    - script: |
        terraform --version
        terraform init 
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Init and Apply'
