trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:

    - script: |
        terraform --version
        az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)
        az account set --subscription $(subscription_id)
        terraform init 
        terraform plan -out=tfplan
      displayName: 'Terraform Init and Plan'

- stage: Deploy
  displayName: 'Terraform Apply'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
        
    - script: |
        terraform --version
        terraform init 
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Init and Apply'
